### ISSUE TITLE
Camera lighting issue

### ISSUE THREAD

**Issue by JamieABall** [SamReha/SnapshotGame#1]
At certain times of day the camera is not visible.

**Comment by ryankwok** [comment]
Sometimes on the first run of the game the ambient lighting does not load correctly, and shadows are pure black. Is this the bug you're referring to?
Even more weird is that usually after stopping and pressing play in the preview window the problem disappears.

Some testing may be necessary to figure out if this is just something that happens in the preview only or the fullscreen exported unity executable as well.

**Comment by ryankwok** [comment]
I've figured out how to replicate the bug!

If there is ambient light:
Press "F" when the game is running. This crashes the game. And spits out the following error. Then ambient light is suddenly gone in the game window.

`UnassignedReferenceException: The variable texture of ScreenOverlay has not been assigned.
You probably need to assign the texture variable of the ScreenOverlay script in the inspector.
UnityEngine.Texture.get_width () (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TextureBindings.gen.cs:50)
UnityEngine.Texture2D.SetPixels (UnityEngine.Color[] colors, Int32 miplevel) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TextureBindings.gen.cs:222)
UnityEngine.Texture2D.SetPixels (UnityEngine.Color[] colors) (at C:/buildslave/unity/build/artifacts/generated/common/runtime/TextureBindings.gen.cs:217)
UnityStandardAssets.ImageEffects.SnapshotCam.Update () (at Assets/The Cam/SnapshotCam.cs:109)`

If there is no ambient light:
Press "F" when the game is not running. Suddenly ambient light appears. If it doesn't, press play, then F, then play again.

**Comment by JamieABall** [comment]
Issue resolved by way of project build.
