### ISSUE TITLE
Errors found in Visible Lines 17 and 42

### ISSUE THREAD

**Issue by JamieABall** [SamReha/SnapshotGame#2]
ArgumentExcption: element already exists
System.Collections.Generic.SortedList` 2[System.Single.UnityEngine.GameObject].PutImpl(Single key, UnityEngine.GameObject value, Boolean overwrite).
The problem reference seem to be "UnobstructedObjs".

**Comment by SamReha** [comment]
Hey Jamie,

This isn't a very descriptive bug report for what appears to be a runtime error. Could you amend this to include reproduction steps?
