### ISSUE TITLE
Player locks in place when entering park (except for the first time)

### ISSUE THREAD

**Issue by SamReha** [SamReha/SnapshotGame#70]
Anytime other than the first time the player enters the park, they find themselves locked in place. They cannot move, but the can look around. The music and day night cycle seem paused while this is happening, as well. The player can work around the issue by toggling pause on and off. Reseting the save without quitting the game does not seem to relieve the issue.

This is probably an issue with the timescale factor persisting incorrectly between scene changes... Solving it is probably as insuring the timescale is set to 1.0 during UIManager.Awake().

**Comment by JamieABall** [comment]
Fixed as of 9/28
